//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gespreksformulier
    {
        public int GespreksformulierID { get; set; }
        public int Stage { get; set; }
        public System.DateTime Datum { get; set; }
        public int ContactType { get; set; }
        public string Gesprek { get; set; }
        public byte[] HandtekeningStudent { get; set; }
        public byte[] HandtekeningDocent { get; set; }
        public byte[] HandtekeningBegeleider { get; set; }
    
        public virtual Stage Stage1 { get; set; }
    }
}
