//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opleiding
    {
        public Opleiding()
        {
            this.OpleidingPersoon = new HashSet<OpleidingPersoon>();
        }
    
        public int OpleidingID { get; set; }
        public string Naam { get; set; }
        public int Niveau { get; set; }
    
        public virtual ICollection<OpleidingPersoon> OpleidingPersoon { get; set; }
    }
}
