//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.Beoordeling = new HashSet<Beoordeling>();
            this.Gespreksformulier = new HashSet<Gespreksformulier>();
            this.TussentijdseBeindeging = new HashSet<TussentijdseBeindeging>();
        }
    
        public int StageID { get; set; }
        public int Student { get; set; }
        public int Stagedocent { get; set; }
        public int Stageperiode { get; set; }
        public int Stagebegeleider { get; set; }
    
        public virtual ICollection<Beoordeling> Beoordeling { get; set; }
        public virtual ICollection<Gespreksformulier> Gespreksformulier { get; set; }
        public virtual Periode Periode { get; set; }
        public virtual Persoonsgegevens Persoonsgegevens { get; set; }
        public virtual Persoonsgegevens Persoonsgegevens1 { get; set; }
        public virtual Persoonsgegevens Persoonsgegevens2 { get; set; }
        public virtual ICollection<TussentijdseBeindeging> TussentijdseBeindeging { get; set; }
    }
}
